const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("streamingBrowser", {
  init: () => ipcRenderer.invoke("app:init"),
  showHome: () => ipcRenderer.invoke("app:show-home"),
  setBrowserBounds: (bounds) => ipcRenderer.invoke("layout:set-browser-bounds", bounds),
  setSettingsOpen: (isOpen) => ipcRenderer.invoke("settings:set-open", isOpen),
  setShellOpen: (isOpen) => ipcRenderer.invoke("shell:set-open", isOpen),
  openProvider: (id) => ipcRenderer.invoke("provider:open", id),
  openProviderSearch: (id, query) => ipcRenderer.invoke("provider:search", id, query),
  openProviderUrl: (id, url) => ipcRenderer.invoke("provider:navigate", id, url),
  searchAll: (query) => ipcRenderer.invoke("search:all", query),
  loadCalendar: (refresh = false) => ipcRenderer.invoke("calendar:load", refresh),
  getRecommendations: (options = {}) => ipcRenderer.invoke("discover:recommendations", options),
  getPersonalRecommendations: (options = {}) => ipcRenderer.invoke("discover:personal", options),
  onPersonalUpdated: (callback) => ipcRenderer.on("discover:personal-updated", () => callback()),
  getPersonalPage: (options = {}) => ipcRenderer.invoke("discover:personal-page", options),
  getWatchpartyStatus: () => ipcRenderer.invoke("watchparty:status"),
  getWatchpartyItems: () => ipcRenderer.invoke("watchparty:items"),
  openWatchpartyItem: (key, room) => ipcRenderer.invoke("watchparty:open", key, room),
  getWatchpartyRooms: () => ipcRenderer.invoke("watchparty:rooms"),
  shareCurrentToWatchparty: (room, punkt) => ipcRenderer.invoke("watchparty:share-current", room, punkt),
  enterWatchparty: (key, room) => ipcRenderer.invoke("watchparty:enter", key, room),
  leaveWatchparty: (key, room) => ipcRenderer.invoke("watchparty:leave", key, room),
  removeFromWatchparty: (key, room) => ipcRenderer.invoke("watchparty:remove", key, room),
  toggleWatchpartyLive: (key, an, room) => ipcRenderer.invoke("watchparty:live-toggle", key, an, room),
  chooseWatchpartyRoom: (rooms, punkt) => ipcRenderer.invoke("watchparty:choose-room", rooms, punkt),
  switchWatchpartyContext: (punkt) => ipcRenderer.invoke("watchparty:switch-context", punkt),
  resyncWatchparty: (key, room) => ipcRenderer.invoke("watchparty:resync", key, room),
  kickFromWatchparty: (key, memberId, room) => ipcRenderer.invoke("watchparty:kick", key, memberId, room),
  onWatchpartyState: (callback) => ipcRenderer.on("watchparty:state", (_event, state) => callback(state)),
  onWatchpartyItems: (callback) => ipcRenderer.on("watchparty:items", (_event, items) => callback(items)),
  chooseWatchpartyMember: (kandidaten, punkt) => ipcRenderer.invoke("watchparty:choose-member", kandidaten, punkt),
  handoverWatchpartyHost: (key, memberId, room) => ipcRenderer.invoke("watchparty:handover", key, memberId, room),
  onWatchpartyLive: (callback) => ipcRenderer.on("watchparty:live", (_event, info) => callback(info)),
  onWatchpartyWatchstate: (callback) => ipcRenderer.on("watchparty:watchstate", (_event, info) => callback(info)),
  // Die YouTube-Watchparty. Eigener Modus, eigene Kanaele - nichts davon geht
  // durch die Steuerung der Watchparty fuer Serien.
  getYoutubePartyStatus: () => ipcRenderer.invoke("youtubeparty:status"),
  setYoutubePartyRoom: (room) => ipcRenderer.invoke("youtubeparty:set-room", room),
  resyncYoutubeParty: () => ipcRenderer.invoke("youtubeparty:resync"),
  openYoutubeParty: () => ipcRenderer.invoke("youtubeparty:open"),
  onYoutubePartyState: (callback) => ipcRenderer.on("youtubeparty:state", (_event, state) => callback(state)),
  navigate: (input) => ipcRenderer.invoke("browser:navigate", input),
  browserCommand: (command) => ipcRenderer.invoke("browser:command", command),
  toggleCurrentFavorite: () => ipcRenderer.invoke("favorites:toggle-current"),
  removeFavorite: (id) => ipcRenderer.invoke("favorites:remove", id),
  removeFromLibrary: (id) => ipcRenderer.invoke("library:remove", id),
  clearNewEpisodeHint: (id) => ipcRenderer.invoke("favorites:clear-new", id),
  markFavoriteCompleted: (id) => ipcRenderer.invoke("favorites:mark-completed", id),
  setFavoriteWatchlist: (id, wert) => ipcRenderer.invoke("favorites:set-watchlist", id, wert),
  setFavoriteImage: (id, dataUrl, crop) => ipcRenderer.invoke("favorites:set-image", id, dataUrl, crop),
  setFavoriteImageCrop: (id, crop) => ipcRenderer.invoke("favorites:set-image-crop", id, crop),
  addSearchResultToWatchlist: (treffer) => ipcRenderer.invoke("favorites:add-result", treffer),
  reorderLibrary: (ids) => ipcRenderer.invoke("library:reorder", ids),
  hideFromContinue: (id) => ipcRenderer.invoke("continue:hide", id),
  clearHistory: () => ipcRenderer.invoke("history:clear"),
  openFavorite: (id, options = {}) => ipcRenderer.invoke("favorites:open", id, options),
  repairFavoriteThumbnail: (id, force = false) => ipcRenderer.invoke("favorites:repair-thumbnail", id, force),
  saveProviders: (providers) => ipcRenderer.invoke("provider:save-all", providers),
  saveSettings: (settings) => ipcRenderer.invoke("settings:save", settings),
  checkForUpdates: () => ipcRenderer.invoke("updates:check"),
  updateFilters: () => ipcRenderer.invoke("adblock:update-filters"),
  getBlocked: () => ipcRenderer.invoke("adblock:blocked"),
  getMediaDiagnostics: () => ipcRenderer.invoke("media:diagnostics"),
  clearCache: () => ipcRenderer.invoke("data:clear-cache"),
  openDataFolder: () => ipcRenderer.invoke("data:open-folder"),
  openHelpIssues: () => ipcRenderer.invoke("help:open-issues"),
  exportBackup: () => ipcRenderer.invoke("data:backup-export"),
  importBackup: () => ipcRenderer.invoke("data:backup-import"),
  resetData: () => ipcRenderer.invoke("data:confirm-reset"),
  onBrowserState: (callback) => ipcRenderer.on("browser:state", (_event, state) => callback(state)),
  onBlocked: (callback) => ipcRenderer.on("adblock:blocked", (_event, items) => callback(items)),
  onMediaDiagnostics: (callback) => ipcRenderer.on("media:diagnostics", (_event, items) => callback(items)),
  onFullscreen: (callback) => ipcRenderer.on("browser:fullscreen", (_event, enabled) => callback(enabled)),
  onUpdateState: (callback) => ipcRenderer.on("updates:state", (_event, state) => callback(state)),
  // Ein Klick auf die Benachrichtigung ueber eine neue Folge. Der Hauptprozess
  // holt das Fenster nach vorn und schickt hierher, um welchen Titel es ging.
  onZeigeFavorit: (callback) => ipcRenderer.on("elfix:zeige-favorit", (_event, id) => callback(id)),
  onToast: (callback) => ipcRenderer.on("app:toast", (_event, message) => callback(message)),
  onAutostartDone: (callback) => ipcRenderer.on("app:autostart-done", (_event, info) => callback(info))
});
